import {test,expect} from './audit-fixtures';
for(const kind of ['learner','guardian','colleague'])for(const failure of ['offline','expired-session','lost-ack'])test(`${kind} invitation ${failure}: visible failure then retry grants one access`,async({page,context})=>{
 const owner=await context.newPage();await owner.goto('/');await owner.getByRole('button',{name:kind==='learner'?'Другой преподаватель · демо':'Я преподаватель',exact:true}).click();await owner.getByRole('button',{name:'Ученики',exact:true}).click();let code='',field='',button='',path='';
 if(kind==='learner'){await owner.getByRole('button',{name:'Пригласить ученика',exact:true}).click();code=await owner.locator('.invite-box code').innerText();field='Код приглашения';button='Принять приглашение';path='/api/invitations/accept';}
 else if(kind==='guardian'){await owner.getByRole('button',{name:/Саша • демо/}).click();await owner.getByRole('button',{name:'Создать приглашение родителю',exact:true}).click();code=await owner.getByLabel('Код родителя',{exact:true}).inputValue();field='Код приглашения родителю';button='Принять доступ';path='/api/guardian/accept';}
 else{await owner.getByLabel('Название пространства').fill('Доставка приглашений');await owner.getByRole('button',{name:'Создать пространство',exact:true}).click();await owner.getByRole('button',{name:'Пригласить коллегу',exact:true}).click();code=await owner.getByLabel('Код для коллеги').inputValue();field='Код пространства';button='Вступить в пространство';path='/api/workspaces/accept';}
 const login=async()=>{await page.getByRole('button',{name:kind==='learner'?'Я ученик':kind==='guardian'?'Я родитель':'Другой преподаватель · демо',exact:true}).click();};
 const prepare=async()=>{if(kind==='learner')await page.getByRole('button',{name:/Саша • демо/}).click();else if(kind==='colleague')await page.getByRole('button',{name:'Ученики',exact:true}).click();await page.getByLabel(field,{exact:true}).fill(code);if(kind==='learner')await page.getByRole('button',{name:'Посмотреть приглашение',exact:true}).click();};
 await page.goto('/');await login();await prepare();
 if(failure==='offline')await context.setOffline(true);
 if(failure==='expired-session')expect(await page.evaluate(async()=>(await fetch('/api/logout',{method:'POST',headers:{Authorization:'Bearer '+sessionStorage.getItem('reprep.session')}})).status)).toBe(200);
 if(failure==='lost-ack')await page.route('**'+path,async r=>{expect((await r.fetch()).ok()).toBe(true);await r.abort();});
 try{await page.getByRole('button',{name:button,exact:true}).click();await expect(page.getByRole('alert').first()).toBeVisible();await expect(page.getByLabel(field,{exact:true})).toHaveValue(code);}finally{await context.setOffline(false);}
 await page.unroute('**'+path);if(failure==='expired-session'){await page.reload();await login();await prepare();}
 await page.getByRole('button',{name:button,exact:true}).click();
 const verify=async(reload=false)=>{if(kind==='learner'){if(!reload)await expect(page.getByText('Вы подключились к преподавателю',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Мой прогресс',exact:true}).click();await expect(page.locator('.learner-list button')).toHaveCount(2);await expect(page.getByRole('button',{name:/Другой репетитор • демо/})).toHaveCount(1);}else if(kind==='guardian'){await expect(page.getByRole('button',{name:/Саша • демо/})).toHaveCount(1);await page.getByRole('button',{name:/Саша • демо/}).click();await expect(page.getByRole('heading',{name:'Расписание ученика',exact:true})).toBeVisible();}else{if(reload)await page.getByRole('button',{name:'Ученики',exact:true}).click();await expect(page.getByRole('combobox',{name:'Текущее пространство',exact:true})).toHaveText('Доставка приглашений');}};
 await verify();await page.reload();await verify(true);await owner.close();
});
