import {test,expect,choose} from './audit-fixtures';
test('group bulk forms validate, preserve the other draft, retry lost ACK and clear warnings only after success',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Я преподаватель',exact:true}).click();await page.getByRole('button',{name:'Ученики',exact:true}).click();await page.getByLabel('Название группы').fill('Общий урок 🧪');await page.getByRole('checkbox',{name:/Саша • демо/}).check();await page.getByRole('checkbox',{name:/Женя • демо/}).check();await page.getByRole('button',{name:'Сохранить группу',exact:true}).click();const group=page.locator('article').filter({has:page.getByRole('heading',{name:'Общий урок 🧪',exact:true})});await expect(group).toBeVisible();
 let posts=0;page.on('request',r=>{if(r.method()==='POST'&&/\/api\/groups\/[^/]+\/(assign|lessons)$/.test(r.url()))posts++;});
 await group.getByRole('button',{name:'Запланировать для всех 2 участников',exact:true}).click();expect(posts).toBe(0);await group.getByRole('button',{name:'Назначить работу всем 2 участникам',exact:true}).click();expect(posts).toBe(0);await page.keyboard.press('Escape');
 const topic=group.getByLabel('Тема общего занятия');await topic.fill('я'.repeat(200));expect((await topic.inputValue()).length).toBe(160);const title='Общий разбор <>& 🧪';await topic.fill(title);await group.getByLabel('Начало общего занятия').fill('2026-10-20T15:00');await group.getByLabel('Длительность общего занятия').fill('5');await group.getByRole('button',{name:'Запланировать для всех 2 участников',exact:true}).click();expect(posts).toBe(0);await group.getByLabel('Длительность общего занятия').fill('60');
 await choose(group.getByRole('combobox',{name:'Работа для группы Общий урок 🧪',exact:true}),'demo-assignment');await group.getByRole('button',{name:'Назначить работу всем 2 участникам',exact:true}).click();await expect(page.getByText('Создано записей для участников: 2',{exact:true})).toBeVisible();
 let asked=0;page.once('dialog',async d=>{asked++;await d.dismiss();});await page.getByRole('button',{name:'Расписание',exact:true}).click();expect(asked).toBe(1);await expect(topic).toHaveValue(title);
 await page.route('**/api/groups/*/lessons',async route=>{expect((await route.fetch()).ok()).toBe(true);await route.abort();});await group.getByRole('button',{name:'Запланировать для всех 2 участников',exact:true}).click();await expect(page.getByRole('alert').first()).toBeVisible();await expect(topic).toHaveValue(title);
 await page.unroute('**/api/groups/*/lessons');await group.getByRole('button',{name:'Запланировать для всех 2 участников',exact:true}).dblclick();await expect(page.getByText('Создано записей для участников: 2',{exact:true})).toBeVisible();
 page.on('dialog',async d=>{asked++;await d.dismiss();});await page.getByRole('button',{name:'Расписание',exact:true}).click();await expect(page.getByRole('heading',{name:'Расписание',exact:true})).toBeVisible();expect(asked).toBe(1);await expect(page.getByRole('heading',{name:title,exact:true})).toHaveCount(2);await page.reload();await page.getByRole('button',{name:'Расписание',exact:true}).click();await expect(page.getByRole('heading',{name:title,exact:true})).toHaveCount(2);
});
