import {test,expect,choose} from './audit-fixtures';
for(const kind of ['edit','assign','lessons'])test(`group ${kind}: stale second tab cannot use the previous membership`,async({page,context})=>{
 await page.goto('/');await page.getByRole('button',{name:'Я преподаватель',exact:true}).click();await page.getByRole('button',{name:'Ученики',exact:true}).click();await page.getByLabel('Название группы').fill('Группа двух вкладок');await page.getByRole('checkbox',{name:/Саша • демо/}).check();await page.getByRole('checkbox',{name:/Женя • демо/}).check();await page.getByRole('button',{name:'Сохранить группу',exact:true}).click();await expect(page.getByRole('heading',{name:'Группа двух вкладок',exact:true})).toBeVisible();
 const other=await context.newPage();await other.goto('/');await other.getByRole('button',{name:'Я преподаватель',exact:true}).click();await other.getByRole('button',{name:'Ученики',exact:true}).click();const group=(p:typeof page,title:string)=>p.locator('article').filter({has:p.getByRole('heading',{name:title,exact:true})});const stale=group(other,'Группа двух вкладок');await expect(stale).toBeVisible();
 const fill=async(g:ReturnType<typeof group>)=>{if(kind==='assign')await choose(g.getByRole('combobox'),'demo-assignment');else if(kind==='lessons'){await g.getByLabel('Тема общего занятия').fill('Занятие нового состава');await g.getByLabel('Начало общего занятия').fill('2026-10-20T15:00');}};
 if(kind==='edit'){await stale.getByRole('button',{name:'Изменить состав',exact:true}).click();await other.getByLabel('Название группы').fill('Устаревшая правка');}else await fill(stale);
 await group(page,'Группа двух вкладок').getByRole('button',{name:'Изменить состав',exact:true}).click();await page.getByLabel('Название группы').fill('Новый состав');await page.getByRole('checkbox',{name:/Женя • демо/}).uncheck();await page.getByRole('button',{name:'Сохранить группу',exact:true}).click();await expect(group(page,'Новый состав')).toBeVisible();
 await (kind==='edit'?other.getByRole('button',{name:'Сохранить группу',exact:true}):stale.getByRole('button',{name:kind==='assign'?'Назначить работу всем 2 участникам':'Запланировать для всех 2 участников',exact:true})).click();await expect(other.getByRole('alert').first()).toBeVisible();if(kind==='edit')await expect(other.getByLabel('Название группы')).toHaveValue('Устаревшая правка');
 await page.reload();await page.getByRole('button',{name:'Ученики',exact:true}).click();await expect(group(page,'Новый состав')).toBeVisible();await expect(group(page,'Новый состав')).not.toContainText('Женя');await page.getByRole('button',{name:kind==='lessons'?'Расписание':/^Задания(?: \d+)?$/,exact:true}).click();if(kind==='lessons')await expect(page.getByRole('heading',{name:'Занятие нового состава',exact:true})).toHaveCount(0);else await expect(page.locator('.assignment-row')).toHaveCount(2);
 other.on('dialog',d=>d.accept());await other.reload();await other.getByRole('button',{name:'Ученики',exact:true}).click();const fresh=group(other,'Новый состав');await expect(fresh).toBeVisible();await expect(fresh).not.toContainText('Женя');
 if(kind!=='edit'){await fill(fresh);await fresh.getByRole('button',{name:kind==='assign'?'Назначить работу всем 1 участникам':'Запланировать для всех 1 участников',exact:true}).click();await expect(other.getByText('Создано записей для участников: 1',{exact:true})).toBeVisible();}
 await other.close();
});
