import {test,expect,choose} from './audit-fixtures';
for(const kind of ['edit','assign','lessons'])test(`tutor cannot ${kind} another teacher group using a substituted group id`,async({page,request})=>{
 const other=await request.post('/api/auth/demo/outsider'),student=await request.post('/api/auth/demo/learner');const oh={Authorization:'Bearer '+(await other.json()).token},lh={Authorization:'Bearer '+(await student.json()).token};const inv=await request.post('/api/invitations',{headers:oh,data:{subject:'Чужая связь'}});expect((await request.post('/api/invitations/accept',{headers:lh,data:{token:(await inv.json()).token}})).ok()).toBe(true);const links=await request.get('/api/relationships',{headers:oh});const rid=(await links.json())[0].id;const saved=await request.post('/api/groups',{headers:oh,data:{title:'Приватная группа коллеги',relationship_ids:[rid],client_id:'audit-foreign-group'}});expect(saved.ok()).toBe(true);const foreign=(await saved.json()).id;
 await page.goto('/');await page.getByRole('button',{name:'Я преподаватель',exact:true}).click();await page.getByRole('button',{name:'Ученики',exact:true}).click();await page.getByLabel('Название группы').fill('Моя группа');await page.getByRole('checkbox',{name:/Саша • демо/}).check();await page.getByRole('button',{name:'Сохранить группу',exact:true}).click();const group=page.locator('article').filter({has:page.getByRole('heading',{name:'Моя группа',exact:true})});await expect(group).toBeVisible();
 const suffix=kind==='edit'?'':'/'+kind;await page.route('**/api/groups/**',r=>{if(!['PUT','POST'].includes(r.request().method()))return r.continue();return r.continue({url:new URL('/api/groups/'+foreign+suffix,r.request().url()).href});});
 if(kind==='edit'){await group.getByRole('button',{name:'Изменить состав',exact:true}).click();await page.getByLabel('Название группы').fill('Попытка чужой правки');await page.getByRole('button',{name:'Сохранить группу',exact:true}).click();}
 else if(kind==='assign'){await choose(group.getByRole('combobox'),'demo-assignment');await group.getByRole('button',{name:'Назначить работу всем 1 участникам',exact:true}).click();}
 else{await group.getByLabel('Тема общего занятия').fill('Попытка чужого занятия');await group.getByLabel('Начало общего занятия').fill('2026-10-20T15:00');await group.getByRole('button',{name:'Запланировать для всех 1 участников',exact:true}).click();}
 await expect(page.getByRole('alert').first()).toBeVisible();await expect(page.getByRole('heading',{name:'Приватная группа коллеги',exact:true})).toHaveCount(0);const groups=await request.get('/api/groups',{headers:oh});expect((await groups.json())[0].title).toBe('Приватная группа коллеги');for(const path of ['/api/lessons','/api/assignments']){const res=await request.get(path,{headers:oh});expect(await res.json()).toEqual([]);}
 await page.unroute('**/api/groups/**');page.on('dialog',d=>d.accept());await page.reload();await page.getByRole('button',{name:'Ученики',exact:true}).click();await expect(group).toBeVisible();
});
