import {test,expect,choose} from './audit-fixtures';
test('late review acknowledgement cannot reopen work after tutor leaves for schedule',async({page,context})=>{
 const learner=await context.newPage(),title='Проверка позднего решения';
 await page.goto('/');await page.getByRole('button',{name:'Я преподаватель',exact:true}).click();await page.getByRole('button',{name:'Создать задание',exact:true}).click();await page.getByLabel('Название работы').fill(title);await choose(page.getByRole('combobox',{name:'Ученик',exact:true}),'demo-link');await page.getByLabel('Условие',{exact:true}).fill('Сложите 2+3');await page.getByLabel('Эталонный ответ',{exact:true}).fill('5');await page.getByLabel('Навык',{exact:true}).fill('Сложение');await page.getByRole('button',{name:'Назначить ученику',exact:true}).click();await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();
 await learner.goto('/');await learner.getByRole('button',{name:'Я ученик',exact:true}).click();await learner.getByRole('button',{name:new RegExp(title)}).click();await learner.getByLabel('Ответ на задание 1').fill('5');learner.on('dialog',d=>d.accept());await learner.getByRole('button',{name:'Отправить работу',exact:true}).click();await expect(learner.locator('.work-task .original p')).toHaveText('5');
 await page.reload();await page.getByRole('button',{name:new RegExp(title)}).click();await choose(page.getByRole('combobox',{name:'Результат',exact:true}),'correct');await page.getByLabel('Обратная связь ученику').fill('Проверено до перехода');
 let release!:()=>void,start!:()=>void;const held=new Promise<void>(r=>release=r),seen=new Promise<void>(r=>start=r);
 await page.route('**/api/submissions/*/review',async route=>{const response=await route.fetch();expect(response.ok()).toBe(true);start();await held;await route.fulfill({response});});
 await page.getByRole('button',{name:'Сохранить мою проверку',exact:true}).click();await seen;page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'Расписание',exact:true}).click();await expect(page.getByRole('heading',{name:'Расписание',exact:true})).toBeVisible();
 const refreshed=page.waitForResponse(r=>r.url().endsWith('/api/assignments'));release();await(await refreshed).finished();await page.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));await expect(page.getByRole('heading',{name:'Расписание',exact:true})).toBeVisible();
 await learner.reload();await learner.getByRole('button',{name:new RegExp(title)}).click();await expect(learner.getByText('Проверено до перехода',{exact:true})).toBeVisible();await learner.close();
});
